### ISSUE TITLE
Using the include directive in a questionnaire with the `pick_randomly` option generates an empty question

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus-rst-tools#109]
The following code will generate an empty question
```rst
.. questionnaire:: pick_randomly_1
  :title: Pick question randomly from a pool of questions
  :submissions: 4
  :points-to-pass: 10
  :pick_randomly: 1
  :category: Pool

  This is a questionnaire with the key `1` that grants at maximum 70 points of difficulty A. 
  Students can make at most 4 submissions.
  This exercise is marked passed when 0 points are reached (the default).

  .. include:: pool_of_questions.rst
```
The yaml file will have something like this

```yaml
...
- fields:
...
    - more: '</div></blockquote>

      '
    title: ''
    type: static
...
```
The UI looks like this

![image](https://user-images.githubusercontent.com/10437475/101653493-09b75c00-3a48-11eb-946f-ab32cf827bf4.png)

The text in the questionnaire description is not accurate,  this is just an example
