### ISSUE TITLE
Categories are difficult to configure

### ISSUE THREAD

**Issue by lainets** [apluslms/a-plus-rst-tools#164]
Categories cannot be configured easily. E.g. setting `accept_unofficial_submits` is difficult. `append_content` in conf.py can be used but it is a bit cumbersome.

**Comment by Mankro** [comment]
`append_content` example:
File `conf.py`:
```python
append_content = [
    '_config_aplus/categories.yaml',
]
```

File `_config_aplus/categories.yaml`:
```yaml
categories:
  submit:
    accept_unofficial_submits: True
    status: nototal
  feedback:
    accept_unofficial_submits: True
    confirm_the_level: True
```
